
name: rcgnn
channels: [conda-forge, pytorch]
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.1.4
  - matplotlib=3.8.4
  - scikit-learn=1.3.2
  - pytorch=2.2.2
  - pip
  - pip:
      - ruptures==1.1.9
      - pytest==7.4.4
