optimizer: { name: "adamw", lr: 2e-4, weight_decay: 1e-4, betas: [0.9, 0.95] }
scheduler: { name: "cosine", warmup_epochs: 1 }
batch_size: 8
epochs: 2
patience: 1
seed: 1337
device: "cpu"
log_every: 20
save_best: true
